version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    restart: on-failure

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    restart: on-failure

  consumer:
    build: ./consumer
    depends_on:
      - kafka
    container_name: consumer
    network_mode: "host" 
    restart: on-failure

  producer:
    depends_on:
      - kafka
    build: ./scrape
    container_name: producer
    network_mode: "host" 
    restart: on-failure

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data/db
    restart: on-failure

  backend:
    build: ./backend
    container_name: backend
    restart: on-failure
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  
  frontend:
    build: ./frontend
    container_name: frontend
    restart: on-failure
    ports:
      - "3001:3001"
    depends_on:
      - backend